export const FETCH_DIPLOMAS_SAGA = "FETCH_DIPLOMAS_SAGA";
export const FETCH_DIPLOMAS_SUCCESS = "FETCH_DIPLOMAS_SUCCESS";
export const FETCH_DIPLOMAS_ERROR = "FETCH_DIPLOMAS_ERROR";

export const FETCH_CHECK_IIN_SAGA = "FETCH_CHECK_IIN_SAGA";
export const FETCH_CHECK_IIN_SUCCESS = "FETCH_CHECK_IIN_SUCCESS";
export const FETCH_CHECK_IIN_ERROR = "FETCH_CHECK_IIN_ERROR";

export const FETCH_SEARCH_SAGA = "FETCH_SEARCH_SAGA";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_ERROR = "FETCH_SEARCH_ERROR";

export const FETCH_CANCEL_FILTER_SAGA = "FETCH_CANCEL_FILTER_SAGA";

export const FETCH_GRADUATES_DETAILS_SAGA = "FETCH_GRADUATES_DETAILS_SAGA";
export const FETCH_GRADUATES_DETAILS_SUCCESS = "FETCH_GRADUATES_DETAILS_SUCCESS";
export const FETCH_GRADUATES_DETAILS_ERROR = "FETCH_GRADUATES_DETAILS_ERROR";

export const UPDATE_ATTRIBUTE_GROUP_ERROR = "UPDATE_ATTRIBUTE_GROUP_ERROR";
