export const localization = {
    "kz": {
        share: "Бөлісу",
        copy:"Сілтемені көшіру",
        shareText: "Бұл жетістікті әлеуметтік желіде бөлісіңіз",
        emailSubject: "Платформаға шағымдау",
        tgTitle: "Платформаға шағымдау",
        wpTitle: "Платформаға шағымдау",
        liTitle: "Платформаға шағымдау",
        liSummary: "Платформаға шағымдау",
    },
    "ru": {
        share:"Поделиться",
        copy:"Скопировать ссылку",
        shareText:"Поделитесь этим достижением в социальной сети",
        emailSubject:"Приглашение на платформу",
        tgTitle: "Приглашение на платформу",
        wpTitle: "Приглашение на платформу",
        liTitle: "Приглашение на платформу",
        liSummary: "Приглашение на платформу",
    },
    "en": {
        share: "Share",
        copy:"Copy link",
        shareText: "Share this achievement on social media",
        emailSubject: "Invitation to the platform",
        tgTitle: "Invitation to the platform",
        wpTitle: "Invitation to the platform",
        liTitle: "Invitation to the platform",
        liSummary: "Invitation to the platform",
    },
}