// FETCH PICKUP TIME
export const FETCH_PICKUP_TIME = "FETCH_PICKUP_TIME";
export const FETCH_PICKUP_TIME_SUCCESS = "FETCH_PICKUP_TIME_SUCCESS";
export const FETCH_PICKUP_TIME_ERROR = "FETCH_PICKUP_TIME_ERROR";
export const UPDATE_PICKUP_TIME = "UPDATE_PICKUP_TIME";
export const UPDATE_PICKUP_TIME_SUCCESS = "UPDATE_PICKUP_TIME_SUCCESS";
export const UPDATE_PICKUP_TIME_ERROR = "UPDATE_PICKUP_TIME_ERROR";
