const appRoot = '/app';

export const routes: Record<string, string> = {
	login: `/auth/login`,
	register: `/auth/register`,
	passwordReset: `/auth/password-reset`,
	main: `${appRoot}/main`,
	hrBank: `${appRoot}/hr-bank`,
	diplomaDetails: `${appRoot}/diploma/:id`,
	university: `${appRoot}/university`,
	universityDetails: `${appRoot}/university/1/detail`,
	universityProfileSecond: `${appRoot}/university/2/profile`,
	aboutUs: `${appRoot}/about-us`,
	vacancies: `${appRoot}/vacancies`,
	news: `${appRoot}/news`,
	addingGraduates: `${appRoot}/addingGraduates`,
	settings: `${appRoot}/settingsPage`,
	notifications: `${appRoot}/notifications`,
	student: `${appRoot}/student/1/details`,
	employer: `${appRoot}/employer/1/details`,
	universityProfile: `${appRoot}/university/1/profile`,
	analysisPage: `${appRoot}/analysisPage`
	//universityDetails: `${appRoot}/university/:id/detail`,
	//aboutUs: `${appRoot}/about-us`,
	//addingGraduates: `${appRoot}/university/graduates/add`,
	//settings: `${appRoot}/user/settings`,
	//profile: `${appRoot}/user/profile`,
	//studentProfile: `${appRoot}/user/profile`,
	//employerProfile: `${appRoot}/user/profile`,
	//universityProfile: `${appRoot}/user/profile`,
	// vacancies: `${appRoot}/vacancies`,
	// news: `${appRoot}/news`,
	// notifications: `${appRoot}/user/notifications`,
};
