const appRoot = '';

export const routes: Record<string, string> = {
	login: `/auth/login`,
	register: `/auth/register`,
	passwordReset: `/auth/password-reset`,
	main: `${appRoot}/main`,
	hrBank: `${appRoot}/hr-bank`,
	diplomaDetails: `${appRoot}/diploma/:id`,
	university: `${appRoot}/university`,
	universityDetails: `${appRoot}/university/:id`,
	universityProfileSecond: `${appRoot}/university/profile`,
	aboutUs: `${appRoot}/about-us`,
	vacancies: `${appRoot}/vacancies`,
	news: `${appRoot}/news`,
	notifications: `${appRoot}/notifications`,
	student: `${appRoot}/student/:id`,
	employer: `${appRoot}/employer/:id`,
	analysisPage: `${appRoot}/analysisPage`,
	// universityDetails: `${appRoot}/university/:id/detail`,
	// aboutUs: `${appRoot}/about-us`,
	addingGraduates: `${appRoot}/university/graduates/add`,
	settings: `${appRoot}/user/settings`,
	profile: `${appRoot}/user/profile`,
	studentProfile: `${appRoot}/user/profile`,
	employerProfile: `${appRoot}/user/profile`,
	universityProfile: `${appRoot}/user/profile`,
	// universityProfile: `${appRoot}/user/profile`,
	// vacancies: `${appRoot}/vacancies`,
	// news: `${appRoot}/news`,
	// notifications: `${appRoot}/user/notifications`,
	aiChat: `${appRoot}/ai-chat`,
};
