//FETCH LOCATIONS
export const FETCH_LOCATIONS_SAGA = "FETCH_LOCATIONS_SAGA";
export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS";

// FETCH ALL LOCATIONS 
export const FETCH_ALL_LOCATIONS_SAGA = "FETCH_ALL_LOCATIONS_SAGA";
export const FETCH_PICKUP_TIME = "FETCH_PICKUP_TIME";
export const FETCH_ALL_LOCATIONS = "FETCH_ALL_LOCATIONS";
export const FETCH_ALL_LOCATIONS_SUCCESS = "FETCH_ALL_LOCATIONS_SUCCESS";
export const FETCH_ALL_LOCATIONS_ERROR = "FETCH_ALL_LOCATIONS_ERROR";

//
export const DELETE_LOCATION_SAGA = "DELETE_LOCATION_SAGA";

// 
export const SET_LOCATION_DRAWER_LOADING = "SET_LOCATION_DRAWER_LOADING";

// CURRENT LOCATION

export const SET_CURR_LOCATION = "SET_CURR_LOCATION";

// POST LOCATIONS => ADD REUSTARANT
export const ADD_LOCATION_REQUEST_SAGA = "ADD_LOCATION_REQUEST_SAGA";

export const SEND_LOCATION_DATA = "SEND_LOCATION_DATA";
export const SEND_LOCATION_DATA_SUCCESS = "SEND_LOCATION_DATA_SUCCESS";
export const SEND_LOCATION_DATA_ERROR = "SEND_LOCATION_DATA_ERROR";

// GET CITY LIST
export const FETCH_CITIES_SAGA = "FETCH_CITIS_SAGA";

export const FETCH_CITIES = "FETCH_CITIES";
export const FETCH_CITIES_SUCCESS = "FETCH_CITIES_SUCCESS";
export const FETCH_CITIES_ERROR = "FETCH_CITIES_ERROR";


// GET IIKO ORGANIZATIONS
export const FETCH_ORGANIZATION_SAGA = "FETCH_ORGANIZATION_SAGA";

export const FETCH_ORGANIZATIONS = "FETCH_ORGANIZATIONS";
export const FETCH_ORGANIZATIONS_SUCCESS = "FETCH_ORGANIZATIONS_SUCCESS";
export const FETCH_ORGANIZATIONS_ERROR = "FETCH_ORGANIZATIONS_ERROR";

export const FETCH_CASH_SYSTEM_SUCCESS = "FETCH_CASH_SYSTEM_SUCCESS";
export const FETCH_CASH_SYSTEM_SAGA = "FETCH_CASH_SYSTEM_SAGA";

//GET AGGREGATOR PAYMENT_TYPES
export const FETCH_PAYMENT_TYPES = "FETCH_PAYMENT_TYPES";
export const FETCH_PAYMENT_TYPES_SUCCESS = "FETCH_PAYMENT_TYPES_SUCCESS";
export const FETCH_PAYMENT_TYPES_ERROR = "FETCH_PAYMENT_TYPES_ERROR";
export const FETCH_PAYMENT_TYPES_SAGA = "FETCH_PAYMENT_TYPES_SAGA";

// SEND IIKO ORGANIZATIONS
export const SEND_IIKO_ORGANIZATIONS_SAGA = "SEND_IIKO_ORGANIZATIONS_SAGA";

export const SEND_IIKO_ORGANIZATIONS = "SEND_IIKO_ORGANIZATIONS";
export const SEND_IIKO_ORGANIZATIONS_SUCCESS = "SEND_IIKO_ORGANIZATIONS";
export const SEND_IIKO_ORGANIZATIONS_ERROR = "SEND_IIKO_ORGANIZATIONS_ERROR";

// Disable Location Integration
export const SWITCH_LOCATION_INTEGRATION_MODE = "SWITCH_LOCATION_INTEGRATION_MODE";

// CREATE GLOVO INTEGRATION
export const CREATE_GLOVO_INTEGRATION = "CREATE_GLOVO_INTEGRATION";
export const CREATE_WOLT_INTEGRATION_SAGA = "CREATE_WOLT_INTEGRATION_SAGA";
export const CREATE_GLOVO_INTEGRATION_SUCCESS = "CREATE_GLOVO_INTEGRATION_SUCCESS";

// GET LOCATION BY ID 
export const GET_LOCATION_BY_ID_SAGA = "GET_LOCATION_BY_ID_SAGA";
export const GET_LOCATION_BY_ID_SUCCESS = "GET_LOCATION_BY_ID_SUCCESS";

// EDIT LOCATION
export const EDIT_LOCATION_ITEM_SAGA = "EDIT_LOCATION_ITEM_SAGA";
// CLEAN LOCATIONFORM
export const CLEAN_LOCATION_FORM = "CLEAN_LOCATION_FORM";

// SUBMIT BTN STATUS 
export const SET_NEXT_IN_PROGRESS_LOADER = "SET_NEXT_IN_PROGRESS_LOADER";

//
export const EDIT_CASH_SYSTEM_SAGA = "EDIT_CASH_SYSTEM_SAGA";

export const PATCH_INTEGRATION_SAGA = "PATCH_INTEGRATION_SAGA";

// GET CURRENCIES LANGUAGES
export const GET_LANGUAGES_SAGA = "GET_LANGUAGES_SAGA";
export const GET_LANGUAGES_SUCCESS = "GET_LANGUAGES_SUCCESS";

export const GET_CURRENCIES_SAGA = "GET_CURRENCIES_SAGA";
export const GET_CURRENCIES_SUCCESS = "GET_CURRENCIES_SUCCESS";

export const GET_WOLT_STATUSSES_SAGA = "GET_WOLT_STATUSSES_SAGA";
export const GET_WOLT_STATUSSES_SUCCESS = "GET_WOLT_STATUSSES_SUCCESS";