export const specialities = {
	"kz": [
		{ id: 1, name: "Қимиялық материалдардың технологиясы" },
		{ id: 2, name: "Геология және пайдаланыстық тамырларды тарату" },
		{ id: 3, name: "Маркетинг" },
		{ id: 4, name: "Менеджмент" },
		{ id: 5, name: "Тіркеу және аудит" },
		{ id: 6, name: "Ұжымдық" },
		{ id: 7, name: "Ұжымдық және экономика" },
		{ id: 8, name: "Экономика" },
		{ id: 9, name: "Бизнесдегі ақпараттық жүйелер" },
		{ id: 10, name: "Экономикалық-математикалық және компьютерлік модельдеу" },
		{ id: 11, name: "Математикалық және компьютерлік модельдеу" },
		{ id: 12, name: "Кемеулік" },
		{ id: 13, name: "Кемеулік энергетикалық орнытасуды өңдеу" },
		{ id: 14, name: "Деу-техника және технология" },
		{ id: 15, name: "Автоматизация және басқару" },
		{ id: 16, name: "Есептеу техникасы және бағдарламалық қамтамасыз ету" },
		{ id: 17, name: "Ақпараттық жүйелер" },
		{ id: 18, name: "Нефтегаз ісі" },
		{ id: 19, name: "Программалық жасақтар" },
		{ id: 20, name: "Компьютерлік ғылым және деректі анализ" },
		{ id: 21, name: "ИТ-те менеджмент" },
		{ id: 22, name: "Проектті басқару" },
		{ id: 23, name: "Басшылар үшін бизнес әкімшілігі" },
		{ id: 24, name: "Материалдар және жаңа материалдар технологиясы" },
		{ id: 25, name: "Наноматериалдар және нанотехнологиялар" },
	],
	"ru": [
		{ id: 1, name: "Химическая технология органических веществ", },
		{ id: 2, name: "Геология и разведка месторождений полезных ископаемых", },
		{ id: 3, name: "Маркетинг", },
		{ id: 4, name: "Менеджмент", },
		{ id: 5, name: "Учет и аудит", },
		{ id: 6, name: "Финансы", },
		{ id: 7, name: "Финансы и экономика", },
		{ id: 8, name: "Экономика", },
		{ id: 9, name: "Информационные системы в бизнесе", },
		{ id: 10, name: "Экономико-математическое и компьютерное моделирование", },
		{ id: 11, name: "Математическое и компьютерное моделирование", },
		{ id: 12, name: "Судовождение", },
		{ id: 13, name: "Эксплуатация судовых энергетических установок", },
		{ id: 14, name: "Морская техника и технологии", },
		{ id: 15, name: "Автоматизация и управление", },
		{ id: 16, name: "Вычислительная техника и программное обеспечение", },
		{ id: 17, name: "Информационные системы", },
		{ id: 18, name: "Нефтегазовое дело", },
		{ id: 19, name: "Программная инженерия", },
		{ id: 20, name: "Компьютерная наука и аналитика данных", },
		{ id: 21, name: "Менеджмент в ИТ", },
		{ id: 22, name: "Управление проектами", },
		{ id: 23, name: "Деловое администрирование для руководителей", },
		{ id: 24, name: "Материаловедение и технология новых материалов", },
		{ id: 25, name: "Наноматериалы и нанотехнологии", },
	],
	"en": [
		{ id: 1, name: "Chemical Technology of Organic Substances" },
		{ id: 2, name: "Geology and Prospecting of Mineral Deposits" },
		{ id: 3, name: "Marketing" },
		{ id: 4, name: "Management" },
		{ id: 5, name: "Accounting and Auditing" },
		{ id: 6, name: "Finance" },
		{ id: 7, name: "Finance and Economics" },
		{ id: 8, name: "Economics" },
		{ id: 9, name: "Information Systems in Business" },
		{ id: 10, name: "Economic-Mathematical and Computer Modeling" },
		{ id: 11, name: "Mathematical and Computer Modeling" },
		{ id: 12, name: "Navigation" },
		{ id: 13, name: "Operation of Ship Power Plants" },
		{ id: 14, name: "Maritime Technology and Technology" },
		{ id: 15, name: "Automation and Control" },
		{ id: 16, name: "Computer Engineering and Software" },
		{ id: 17, name: "Information Systems" },
		{ id: 18, name: "Oil and Gas Business" },
		{ id: 19, name: "Software Engineering" },
		{ id: 20, name: "Computer Science and Data Analytics" },
		{ id: 21, name: "IT Management" },
		{ id: 22, name: "Project Management" },
		{ id: 23, name: "Business Administration for Executives" },
		{ id: 24, name: "Materials Science and Technology of New Materials" },
		{ id: 25, name: "Nanomaterials and Nanotechnology" }
	]

};
export const regions = {
	"kz": [
		{ id: 1, name: "Ақмола облысы" },
		{ id: 2, name: "Ақтөбе облысы" },
		{ id: 3, name: "Алматы облысы" },
		{ id: 4, name: "Алматы" },
		{ id: 5, name: "Астана" },
		{ id: 6, name: "Атырау облысы" },
		{ id: 7, name: "Шығыс Қазақстан облысы" },
		{ id: 8, name: "Жамбыл облысы" },
		{ id: 9, name: "Жезқазған облысы" },
		{ id: 10, name: "Батыс Қазақстан облысы" },
		{ id: 11, name: "Қазақстан" },
		{ id: 12, name: "Қарағанды облысы" },
		{ id: 13, name: "Қарақалпақстан" },
		{ id: 14, name: "Қостанай облысы" },
		{ id: 15, name: "Қызылорда облысы" },
		{ id: 16, name: "Маңғыстау облысы" },
		{ id: 17, name: "Павлодар облысы" },
		{ id: 18, name: "Солтүстік Қазақстан облысы" },
		{ id: 19, name: "Талдықорған облысы" },
		{ id: 20, name: "Түркістан облысы" },
		{ id: 21, name: "Шымкент" },
	],
	"ru": [{ id: 1, name: "Акмолинская обл.", },
	{ id: 2, name: "Актюбинская обл.", },
	{ id: 3, name: "Алматинская область", },
	{ id: 4, name: "Алматы", },
	{ id: 5, name: "Астана", },
	{ id: 6, name: "Атырауская обл.", },
	{ id: 7, name: "Восточно-Казахстанская обл.", },
	{ id: 8, name: "Жамбылская обл.", },
	{ id: 9, name: "Жезказганская обл.", },
	{ id: 10, name: "Западно-Казахстанская обл.", },
	{ id: 11, name: "Казахстан", },
	{ id: 12, name: "Карагандинская обл.", },
	{ id: 13, name: "Каракалпакия", },
	{ id: 14, name: "Костанайская обл.", },
	{ id: 15, name: "Кызылординская обл.", },
	{ id: 16, name: "Мангыстауская обл.", },
	{ id: 17, name: "Павлодарская обл.", },
	{ id: 18, name: "Северо-Казахстанская обл.", },
	{ id: 19, name: "Талдыкорганская обл.", },
	{ id: 20, name: "Туркестанская обл.", },
	{ id: 21, name: "Шымкент", },],
	"en": [
		{ id: 1, name: "Akmola Region" },
		{ id: 2, name: "Aktobe Region" },
		{ id: 3, name: "Almaty Region" },
		{ id: 4, name: "Almaty" },
		{ id: 5, name: "Nur-Sultan" },
		{ id: 6, name: "Atyrau Region" },
		{ id: 7, name: "East Kazakhstan Region" },
		{ id: 8, name: "Zhambyl Region" },
		{ id: 9, name: "Zhezkazgan Region" },
		{ id: 10, name: "West Kazakhstan Region" },
		{ id: 11, name: "Kazakhstan" },
		{ id: 12, name: "Karaganda Region" },
		{ id: 13, name: "Karakalpakstan" },
		{ id: 14, name: "Kostanay Region" },
		{ id: 15, name: "Kyzylorda Region" },
		{ id: 16, name: "Mangystau Region" },
		{ id: 17, name: "Pavlodar Region" },
		{ id: 18, name: "North Kazakhstan Region" },
		{ id: 19, name: "Taldykorgan Region" },
		{ id: 20, name: "Turkistan Region" },
		{ id: 21, name: "Shymkent" },
	]

};
export const years = [
	{
		id: 1,
		year: 2023,
	},
];

export const degree = [
	{ id: 1, name: "Бакалавр" },
	{ id: 2, name: "Магистр" },
];
export const localization = {
	"kz": {
		MainCard: {
			speciality: "Мамандықтар",
			region: "Облыстар",
			year: "Бітірген жылы",
			filter: "Сүзгі",
			apply: "Қолдану",
			university: "Университет",
		}
	},
	"ru": {
		MainCard: {
			speciality: "Специальности",
			region: "Регион",
			year: "Год выпуска",
			filter: "Фильтр",
			apply: "Применить",
			university: "Университет",
		}
	},
	"en": {
		MainCard: {
			speciality: "Specialities",
			region: "Regions",
			year: "Year of Graduation",
			filter: "Filter",
			apply: "Apply",
			university: "Университет",
		}
	},
}

export const universities = {
	"kz":[
		{ id: 1, name: "КБТУ", university_id: 1},
		{ id: 2, name: "АГП", university_id: 2},
		{ id: 3, name: "СУ", university_id: 3},
	],
	"ru":[
		{ id: 1, name: "КБТУ", university_id: 1},
		{ id: 2, name: "АГП", university_id: 2},
		{ id: 3, name: "СУ", university_id: 3},
	],
	"en":[
		{ id: 1, name: "KBTU", university_id: 1},
		{ id: 2, name: "AGP", university_id: 2},
		{ id: 3, name: "SU", university_id: 3},
	],
}

export const fields = {
	"en": [
	  {"id": 1, "name": "Automotive industry"},
	  {"id": 2, "name": "Hospitality and catering"},
	  {"id": 3, "name": "Public sector"},
	  {"id": 4, "name": "Natural resources and energy"},
	  {"id": 5, "name": "Utilities"},
	  {"id": 6, "name": "Technology and IT"},
	  {"id": 7, "name": "Culture and art"},
	  {"id": 8, "name": "Forestry and wood processing industry"},
	  {"id": 9, "name": "Healthcare and pharmaceuticals"},
	  {"id": 10, "name": "Metallurgy and metalworking"},
	  {"id": 11, "name": "Education"},
	  {"id": 12, "name": "Logistics and transport"},
	  {"id": 13, "name": "Food industry"},
	  {"id": 14, "name": "Industrial equipment and mechanical engineering"},
	  {"id": 15, "name": "Retail trade and services"},
	  {"id": 16, "name": "Agriculture"},
	  {"id": 17, "name": "Marketing, media and advertising"},
	  {"id": 18, "name": "Construction and real estate"},
	  {"id": 19, "name": "Telecommunications and communications"},
	  {"id": 20, "name": "Consumer goods"},
	  {"id": 21, "name": "Asset management and business services"},
	  {"id": 22, "name": "Financial sector"},
	  {"id": 23, "name": "Chemical industry"}
	],
	"kz": [
	  {"id": 1, "name": "Автомобиль өнеркәсібі"},
	  {"id": 2, "name": "Қонақжайлылық және қоғамдық тамақтандыру"},
	  {"id": 3, "name": "Мемлекеттік сектор"},
	  {"id": 4, "name": "Табиғи ресурстар және энергия"},
	  {"id": 5, "name": "Утилиталар"},
	  {"id": 6, "name": "Технология және АТ"},
	  {"id": 7, "name": "Мәдениет және өнер"},
	  {"id": 8, "name": "Орман және ағаш өңдеу өнеркәсібі"},
	  {"id": 9, "name": "Денсаулық сақтау және фармацевтика"},
	  {"id": 10, "name": "Металлургия және металл өңдеу"},
	  {"id": 11, "name": "Білім"},
	  {"id": 12, "name": "Логистика және көлік"},
	  {"id": 13, "name": "Тамақ өнеркәсібі"},
	  {"id": 14, "name": "Өнеркәсіптік жабдық және машина жасау"},
	  {"id": 15, "name": "Бөлшек сауда және қызмет көрсету"},
	  {"id": 16, "name": "Ауыл шаруашылығы"},
	  {"id": 17, "name": "Маркетинг, БАҚ және жарнама"},
	  {"id": 18, "name": "Құрылыс және жылжымайтын мүлік"},
	  {"id": 19, "name": "Телекоммуникация және байланыс"},
	  {"id": 20, "name": "Тұтыну тауарлары"},
	  {"id": 21, "name": "Активтерді басқару және бизнес қызметтері"},
	  {"id": 22, "name": "Қаржы секторы"},
	  {"id": 23, "name": "Химия өнеркәсібі"}
	],
	"ru": [
	  {"id": 1, "name": "Автомобильная индустрия"},
	  {"id": 2, "name": "Гостеприимство и общественное питание"},
	  {"id": 3, "name": "Государственный сектор"},
	  {"id": 4, "name": "Природные ресурсы и энергетика"},
	  {"id": 5, "name": "Коммунальные услуги"},
	  {"id": 6, "name": "Технологии и IT"},
	  {"id": 7, "name": "Культура и искусство"},
	  {"id": 8, "name": "Лесная и деревообрабатывающая промышленность"},
	  {"id": 9, "name": "Здравоохранение и фармацевтика"},
	  {"id": 10, "name": "Металлургия и металлообработка"},
	  {"id": 11, "name": "Образование"},
	  {"id": 12, "name": "Логистика и транспорт"},
	  {"id": 13, "name": "Пищевая промышленность"},
	  {"id": 14, "name": "Промышленное оборудование и машиностроение"},
	  {"id": 15, "name": "Розничная торговля и услуги"},
	  {"id": 16, "name": "Сельское хозяйство"},
	  {"id": 17, "name": "Маркетинг, СМИ и реклама"},
	  {"id": 18, "name": "Строительство и недвижимость"},
	  {"id": 19, "name": "Телекоммуникации и связь"},
	  {"id": 20, "name": "Товары народного потребления"},
	  {"id": 21, "name": "Управление активами и бизнес-услуги"},
	  {"id": 22, "name": "Финансовый сектор"},
	  {"id": 23, "name": "Химическая промышленность"}
	],
  };