export const specialities = {
	"kz": [
		{ id: 1, name: "Қимиялық материалдардың технологиясы" },
		{ id: 2, name: "Геология және пайдаланыстық тамырларды тарату" },
		{ id: 3, name: "Маркетинг" },
		{ id: 4, name: "Менеджмент" },
		{ id: 5, name: "Тіркеу және аудит" },
		{ id: 6, name: "Ұжымдық" },
		{ id: 7, name: "Ұжымдық және экономика" },
		{ id: 8, name: "Экономика" },
		{ id: 9, name: "Бизнесдегі ақпараттық жүйелер" },
		{ id: 10, name: "Экономикалық-математикалық және компьютерлік модельдеу" },
		{ id: 11, name: "Математикалық және компьютерлік модельдеу" },
		{ id: 12, name: "Кемеулік" },
		{ id: 13, name: "Кемеулік энергетикалық орнытасуды өңдеу" },
		{ id: 14, name: "Деу-техника және технология" },
		{ id: 15, name: "Автоматизация және басқару" },
		{ id: 16, name: "Есептеу техникасы және бағдарламалық қамтамасыз ету" },
		{ id: 17, name: "Ақпараттық жүйелер" },
		{ id: 18, name: "Нефтегаз ісі" },
		{ id: 19, name: "Программалық жасақтар" },
		{ id: 20, name: "Компьютерлік ғылым және деректі анализ" },
		{ id: 21, name: "ИТ-те менеджмент" },
		{ id: 22, name: "Проектті басқару" },
		{ id: 23, name: "Басшылар үшін бизнес әкімшілігі" },
		{ id: 24, name: "Материалдар және жаңа материалдар технологиясы" },
		{ id: 25, name: "Наноматериалдар және нанотехнологиялар" },
	],
	"ru": [
		{ id: 1, name: "Химическая технология органических веществ", },
		{ id: 2, name: "Геология и разведка месторождения полезных ископаемых", },
		{ id: 3, name: "Маркетинг", },
		{ id: 4, name: "Менеджмент", },
		{ id: 5, name: "Учет и аудит", },
		{ id: 6, name: "Финансы", },
		{ id: 7, name: "Финансы и экономика", },
		{ id: 8, name: "Экономика", },
		{ id: 9, name: "Информационные системы в бизнесе", },
		{ id: 10, name: "Экономико-математическое и компьютерное моделирование", },
		{ id: 11, name: "Математическое и компьютерное моделирование", },
		{ id: 12, name: "Судовождение", },
		{ id: 13, name: "Эксплуатация судовых энергетических установок", },
		{ id: 14, name: "Морская техника и технология", },
		{ id: 15, name: "Автоматизация и управление", },
		{ id: 16, name: "Вычислительная техника и программное обеспечение", },
		{ id: 17, name: "Информационные системы", },
		{ id: 18, name: "Нефтегазовое дело", },
		{ id: 19, name: "Программная инженерия", },
		{ id: 20, name: "Компьютерная наука и аналитика данных ", },
		{ id: 21, name: "Менеджмент в ИТ", },
		{ id: 22, name: "Управление проектами", },
		{ id: 23, name: "Деловое администрирование для руководителей", },
		{ id: 24, name: "Материаловедение и технология новых материалов", },
		{ id: 25, name: "Наноматериалы и нанотехнологии", },
	],
	"en": [
		{ id: 1, name: "Chemical Technology of Organic Substances" },
		{ id: 2, name: "Geology and Prospecting of Mineral Deposits" },
		{ id: 3, name: "Marketing" },
		{ id: 4, name: "Management" },
		{ id: 5, name: "Accounting and Auditing" },
		{ id: 6, name: "Finance" },
		{ id: 7, name: "Finance and Economics" },
		{ id: 8, name: "Economics" },
		{ id: 9, name: "Information Systems in Business" },
		{ id: 10, name: "Economic-Mathematical and Computer Modeling" },
		{ id: 11, name: "Mathematical and Computer Modeling" },
		{ id: 12, name: "Navigation" },
		{ id: 13, name: "Operation of Ship Power Plants" },
		{ id: 14, name: "Maritime Technology and Technology" },
		{ id: 15, name: "Automation and Control" },
		{ id: 16, name: "Computer Engineering and Software" },
		{ id: 17, name: "Information Systems" },
		{ id: 18, name: "Oil and Gas Business" },
		{ id: 19, name: "Software Engineering" },
		{ id: 20, name: "Computer Science and Data Analytics" },
		{ id: 21, name: "IT Management" },
		{ id: 22, name: "Project Management" },
		{ id: 23, name: "Business Administration for Executives" },
		{ id: 24, name: "Materials Science and Technology of New Materials" },
		{ id: 25, name: "Nanomaterials and Nanotechnology" }
	]

};
export const regions = {
	"kz": [
		{ id: 1, name: "Ақмола облысы" },
		{ id: 2, name: "Ақтөбе облысы" },
		{ id: 3, name: "Алматы облысы" },
		{ id: 4, name: "Алматы" },
		{ id: 5, name: "Астана" },
		{ id: 6, name: "Атырау облысы" },
		{ id: 7, name: "Шығыс Қазақстан облысы" },
		{ id: 8, name: "Жамбыл облысы" },
		{ id: 9, name: "Жезқазған облысы" },
		{ id: 10, name: "Батыс Қазақстан облысы" },
		{ id: 11, name: "Қазақстан" },
		{ id: 12, name: "Қарағанды облысы" },
		{ id: 13, name: "Қарақалпақстан" },
		{ id: 14, name: "Қостанай облысы" },
		{ id: 15, name: "Қызылорда облысы" },
		{ id: 16, name: "Маңғыстау облысы" },
		{ id: 17, name: "Павлодар облысы" },
		{ id: 18, name: "Солтүстік Қазақстан облысы" },
		{ id: 19, name: "Талдықорған облысы" },
		{ id: 20, name: "Түркістан облысы" },
		{ id: 21, name: "Шымкент" },
	],
	"ru": [{ id: 1, name: "Акмолинская обл.", },
	{ id: 2, name: "Актюбинская обл.", },
	{ id: 3, name: "Алматинская область", },
	{ id: 4, name: "Алматы", },
	{ id: 5, name: "Астана", },
	{ id: 6, name: "Атырауская обл.", },
	{ id: 7, name: "Восточно-Казахстанская обл.", },
	{ id: 8, name: "Жамбылская обл.", },
	{ id: 9, name: "Жезказганская обл.", },
	{ id: 10, name: "Западно-Казахстанская обл.", },
	{ id: 11, name: "Казахстан", },
	{ id: 12, name: "Карагандинская обл.", },
	{ id: 13, name: "Каракалпакия", },
	{ id: 14, name: "Костанайская обл.", },
	{ id: 15, name: "Кызылординская обл.", },
	{ id: 16, name: "Мангыстауская обл.", },
	{ id: 17, name: "Павлодарская обл.", },
	{ id: 18, name: "Северо-Казахстанская обл.", },
	{ id: 19, name: "Талдыкорганская обл.", },
	{ id: 20, name: "Туркестанская обл.", },
	{ id: 21, name: "Шымкент", },],
	"en": [
		{ id: 1, name: "Akmola Region" },
		{ id: 2, name: "Aktobe Region" },
		{ id: 3, name: "Almaty Region" },
		{ id: 4, name: "Almaty" },
		{ id: 5, name: "Nur-Sultan" },
		{ id: 6, name: "Atyrau Region" },
		{ id: 7, name: "East Kazakhstan Region" },
		{ id: 8, name: "Zhambyl Region" },
		{ id: 9, name: "Zhezkazgan Region" },
		{ id: 10, name: "West Kazakhstan Region" },
		{ id: 11, name: "Kazakhstan" },
		{ id: 12, name: "Karaganda Region" },
		{ id: 13, name: "Karakalpakstan" },
		{ id: 14, name: "Kostanay Region" },
		{ id: 15, name: "Kyzylorda Region" },
		{ id: 16, name: "Mangystau Region" },
		{ id: 17, name: "Pavlodar Region" },
		{ id: 18, name: "North Kazakhstan Region" },
		{ id: 19, name: "Taldykorgan Region" },
		{ id: 20, name: "Turkistan Region" },
		{ id: 21, name: "Shymkent" },
	]

};
export const years = [
	{
		id: 1,
		year: 2023,
	},
];

export const degree = [
	{ id: 1, name: "Бакалавр" },
	{ id: 2, name: "Магистр" },
];
export const localization = {
	"kz": {
		MainCard: {
			speciality: "Мамандықтар",
			region: "Облыстар",
			year: "Бітірген жылы",
			filter: "Сүзгі",
			apply: "Қолдану",
			university: "Университет",
		}
	},
	"ru": {
		MainCard: {
			speciality: "Специальности",
			region: "Регион",
			year: "Год выпуска",
			filter: "Фильтр",
			apply: "Применить",
			university: "Университет",
		}
	},
	"en": {
		MainCard: {
			speciality: "Specialities",
			region: "Regions",
			year: "Year of Graduation",
			filter: "Filter",
			apply: "Apply",
			university: "Университет",
		}
	},
}

export const universities = {
	"kz":[
		{ id: 1, name: "КБТУ", university_id: 1},
		{ id: 2, name: "АГП", university_id: 2},
		{ id: 3, name: "СУ", university_id: 3},
	],
	"ru":[
		{ id: 1, name: "КБТУ", university_id: 1},
		{ id: 2, name: "АГП", university_id: 2},
		{ id: 3, name: "СУ", university_id: 3},
	],
	"en":[
		{ id: 1, name: "KBTU", university_id: 1},
		{ id: 2, name: "AGP", university_id: 2},
		{ id: 3, name: "SU", university_id: 3},
	],
}