export enum SelectAllActionTypes {
  FETCH_SELECT_ALL_LOCATIONS_SAGA = "FETCH_SELECT_ALL_LOCATIONS_SAGA",
  FETCH_SELECT_ALL_LOCATIONS = "FETCH_LOCATIONS",
  FETCH_SELECT_ALL_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS",
  FETCH_SELECT_ALL_LOCATIONS_ERROR = "FETCH_LOCATIONS_ERROR",

  SET_NEW_PRODUCT = "SET_NEW_PRODUCT",
  SET_OLD_PRODUCT = "SET_OLD_PRODUCT"
}